server {
    listen 80;
    server_name localhost;

    # sendfile off : corrige le bug de fichiers servis "vides" (octets nuls)
    # sur certains systèmes de fichiers virtuels (Docker Desktop / WSL2).
    sendfile off;

    location / {
        root   /usr/share/nginx/html;
        index  index.html;
    }
}
